- name: Create user with sudo
  user:
    name: "{{ user }}"
    groups: wheel
    shell: /bin/zsh

- name: Allow passwordless sudo for wheel
  copy:
    content: "%wheel ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/wheel_nopasswd
    validate: "visudo -cf %s"